"""empty message

Revision ID: c8c3c29a37c9
Revises: 0af524808b83
Create Date: 2019-09-27 00:08:07.051792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c3c29a37c9'
down_revision = '0af524808b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comptes',
    sa.Column('id_compte', sa.String(length=50), nullable=False),
    sa.Column('type_compte', sa.Enum('COURANT', 'DECOUVERT', 'INTERET', name='typecompte'), nullable=True),
    sa.Column('rib', sa.String(length=50), nullable=True),
    sa.Column('solde', sa.Float(precision=20), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_compte')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comptes')
    # ### end Alembic commands ###
